# filepath: /Users/furkantunali/Sites/youtube-text/docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    networks:
      - summatube-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./frontend/.env
    networks:
      - summatube-network
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8001/api
      - EXTERNAL_API_URL=http://localhost:8001/api
    healthcheck:
      test: ["CMD", "node", "check-connectivity.js"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  summatube-network:
    driver: bridge
